### ISSUE TITLE
Connection Error after Clean Installation on Debian 10/Buster

### ISSUE THREAD

**Issue by prosperocu** [Wutze/OpenVPN-WebAdmin#19]
Hi people:

This is my Environment:

OS: Debian 10/Buster (clean VPS reinstalled almost right now)
Installation: Step by step of the guide.

This is my apache log error:

"
[Sun Jul 19 23:59:56.499218 2020] [php7:warn] [pid 791] [client 152.206.198.179:5457] PHP Warning:  session_start(): Failed to initialize storage module: user (path: /var/lib/php/sessions) in /srv/www/openvpn-admin/include/class/class.session.php on line 64
"

Note: I have been removed referrer in the log.

**Comment by prosperocu** [comment]
![error openvpnadmin](https://user-images.githubusercontent.com/41196461/87886375-57c0ba00-c9ea-11ea-85cb-feb8103d1c57.png)

**Comment by Wutze** [comment]
You are obviously missing the session2 table in the database.

Please add this in your Database:

https://github.com/Wutze/OpenVPN-WebAdmin/blob/master/sql/adodb.sql

**Comment by Wutze** [comment]
Error in the installation script

**Comment by Wutze** [comment]
Thank you very much for the report. The error is now fixed. Thank you.
