### ISSUE TITLE
Installation fails - Error Insert Database Dump

### ISSUE THREAD

**Issue by pdavisfmnh** [Wutze/OpenVPN-WebAdmin#21]
**Describe the bug**
The database dump is missing a table. There is no create table for the following insert to work:
```
INSERT INTO `usergroups` (`gid`, `uid`, `gname`) VALUES
(1, 1, 1),
(2, 2, 2);
COMMIT;
```

**Comment by Wutze** [comment]
fixed the bug

Thank you ;o)

**Comment by pdavisfmnh** [comment]
Found a few errors in the db dump
is currently:
```INSERT INTO `groupnames` (`gname`, `name`) VALUES```
Should be:
```INSERT INTO `groupnames` (`gid`, `name`) VALUES```

is currently:
```INSERT INTO `log` (`log_id`, `user_id`, `log_trusted_ip`, `log_trusted_port`, `log_remote_ip`, `log_remote_port`, `log_start_time`, `log_end_time`, `log_received`, `log_send`) VALUES```
should be:
```INSERT INTO `log` (`log_id`, `user_name`, `log_trusted_ip`, `log_trusted_port`, `log_remote_ip`, `log_remote_port`, `log_start_time`, `log_end_time`, `log_received`, `log_send`) VALUES```

and removed the above section
this allowed the dump to install.

Then I get 
ERROR 1054 (42S22) at line 1: Unknown column 'user_id' in 'field list'

fixed in the install script:
was:
```mysql -h $db_host -u $mysql_user --password=$mysql_user_pass --database=$db_name -e "INSERT INTO user (user_id, user_pass, gid, user_enable) VALUES ('${admin_user}', encrypt('${admin_user_pass}'),'1','1');"```

change user_id to user_name

**Comment by Wutze** [comment]
Damn, I still missed that. :o(

**Comment by Wutze** [comment]
I think its fixed now.

Edit with MobilPhone from Train. :o)
