### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by mymdent** [Wutze/OpenVPN-WebAdmin#28]
A very nice project, if you are interested in translating into Polish, I am here to help.

**Comment by victorhck** [comment]
Should be enough with a new file in installation/lang ?

**Comment by Wutze** [comment]
Depending on what you want to translate, as the installation and the web frontend each have their own language area. It is therefore not absolutely necessary to have a Russian translation of the web frontend in addition to a Russian translation of the installation, for example. This would be desirable, but it is not obligatory ;o)

Translation of the installation, then a file with the name of the language code (locale-code) to installation/lang/ [locale-code] (example: ru_RU for Russian).

If you want to add another translation of the web frontend, then a file with the name "lang.php" belongs in a separate folder with [locale-code] in the wwwroot/include/lang/ folder.

As an example, Russian again, wwwroot/include/lang/ru_RU/lang.php

**Comment by Wutze** [comment]
Gracias @victorhck, la traducción al español acaba de llegar al repositorio. ¡Muchas gracias! :o)

Thank you @victorhck, the Spanish translation has just arrived in the repository. Thank you very much! :o)

**Comment by victorhck** [comment]
A pleasure! If I can help you with translation in next releases just ping me! ;)
Maybe a next step it's translate doc!
Greetings!

**Comment by Wutze** [comment]
I am happy about these translations, this help. Thank you very much.

**Comment by victorhck** [comment]
> I am happy about these translations, this help. Thank you very much.

Since I'm not a developer, this is the way I can contribute with free software...

**Comment by Wutze** [comment]
> Since I'm not a developer, this is the way I can contribute with free software...

That's what open source lives on ;o)

I love it.
