### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by vicn1222** [Wutze/OpenVPN-WebAdmin#43]
Try to install on CenterOS 8, keep getting error
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

I have already set proper root password will full access. The installer changes it and then can't login.

That is, I already have MariaDB running that have many different databases in there. The installer probably assume this is a brand new system without pre-installed database?

I have websites hosted in this server, can you not assume it is only for openvpn?
The websites has their own databases....

Thanks

**Comment by vicn1222** [comment]
That is, I already have MariaDB running that have many different databases in there. The installer probably assume this is a brand new system without pre-installed database?

**Comment by Wutze** [comment]
Correct, a naked/brand new system is accepted. If you already have a MySQL running somewhere, then it is sufficient to specify a "remote MySQL server" during the installation. This does not have to be reconfigured.
