### ISSUE TITLE
Cannot click any menu or button on Admin dashboard

### ISSUE THREAD

**Issue by dungpt2020** [Wutze/OpenVPN-WebAdmin#46]
Hi guys,

**Describe the bug**

- I installed the first server on 30/06/2021. It's working okay, still today.
- Today, I installed a new server. And after the installation finished, I can login to admin dashboard, but I cannot click any menu or anything on Admin dashboard.

For example, when I click menu `Log`, the dashboard did not change anything and the URL show like `https://vpn.mydomain.com#log`.

**Log file**

I checked the Apache's error log, the file `/var/log/apache2/error.log`, it's showing:

```log
[Thu Jul 22 09:19:01.322802 2021] [php7:notice] [pid 685] [client 42.113.216.123:51489] PHP Notice:  Undefined index: sort in /srv/www/openvpn-admin/include/class/class.data.php on line 89, referer: https://vpn.mydomain.com/
[Thu Jul 22 09:19:01.322873 2021] [php7:notice] [pid 685] [client 42.113.216.123:51489] PHP Notice:  Undefined index: order in /srv/www/openvpn-admin/include/class/class.data.php on line 90, referer: https://vpn.mydomain.com/
```

**Browser console**

Then I check browser console, it's showing like this image.

![Selection_001](https://user-images.githubusercontent.com/75596049/126618313-14f8f5ac-f4d7-4c38-b7f7-8d94bb2ad268.jpg)

File `tab.js` in folder `/srv/www/ovpn_modules/node_modules/bootstrap/js/dist/tab.js`

**Guess cause**

I guess this bug cause by module `bootstrap`. On the old server, folder `bootstrap` just has 4.8 MB size. On the new server, folder `bootstrap` has 8.5 MB size. There is something distinctly different.

**Temp solution**

1. Delete folder `/srv/www/ovpn_modules/node_modules/bootstrap` on the new server.
2. Copy folder `bootstrap` from old server and replace on the new server.

I attached 2 folders to this bug for you guys. 
- The working folder name: [bootstrap_old.tar.gz](https://github.com/Wutze/OpenVPN-WebAdmin/files/6861404/bootstrap_old.tar.gz)
- The folder not working name: [bootstrap_new.tar.gz](https://github.com/Wutze/OpenVPN-WebAdmin/files/6861406/bootstrap_new.tar.gz)

Please compare it and find out the root cause of this bug.

**Server info**

Here is my environment, both servers are same.

- **OS**: 20.04.1 x64 LTS (Focal Fossa)
- **User install**: root
- **RAM**: 4 GB
- **HDD**: 50 GB
- **vCPU**: 2 CPU
- **Reboot after installation**: yes

**Comment by Wutze** [comment]
Thank you. I made a mistake here. The new Bootstrap version should not be online yet.

The remedy is in the folder

```
/srv/www/opvn_modules/
```
edit the file "package.json". Replace the value "bootstrap": "^5.0.2" with 4.5.0. Change to the same folder in the shell and simply execute the command "yarn install". This fixes the error.
