### ISSUE TITLE
There is no user edit button

### ISSUE THREAD

**Issue by shahrooz1349** [Wutze/OpenVPN-WebAdmin#74]
Hello I have been using this admin panel for several months, everything was fine My previous server was filtered and I installed the
panel on my new server but there is no edit button next to the username My version is Debian 10 please guide me 
Regard

![Screenshot_20220624_234015_com android chrome_edit_1037142966596422](https://user-images.githubusercontent.com/87688187/175656229-c68a70ba-4ca6-4a3d-aca7-721663604430.jpg)

**Comment by shahrooz1349** [comment]
![Uploading Screenshot_20220624_234015_com.android.chrome_edit_1037142966596422.jpg…]()

**Comment by shahrooz1349** [comment]
@Wutze

**Comment by shahrooz1349** [comment]
Thanks for any ideas to solve the problem

**Comment by victorhck** [comment]
> Dear friend, thank you very much for this excellent management version, please guide me to solve the problem

Hello, please don't mention to me, I'm just translator, not developer. Hope you can solve your issue, so maybe you can add more info of your system, etc...
thanks

**Comment by shahrooz1349** [comment]
> > Dear friend, thank you very much for this excellent management version, please guide me to solve the problem
> 
> Hello, please don't mention to me, I'm just translator, not developer. Hope you can solve your issue, so maybe you can add more info of your system, etc... thanks

Thank you for your answer my dear friend
Sorry I tagged you 🙏
I have this problem in my new installation on debian 10

**Comment by shahrooz1349** [comment]
dear friends, I welcome any suggestion to solve the problem

**Comment by shahrooz1349** [comment]
🙁☹️

**Comment by shahrooz1349** [comment]
I am really surprised that if you reinstall it, you cannot edit the user
Please contribute

**Comment by shahrooz1349** [comment]
Users cannot be edited, you cannot delete or change the date I tested both in Cento 8 and Debian 10
