### ISSUE TITLE
There is no edit user button

### ISSUE THREAD

**Issue by shahrooz1349** [Wutze/OpenVPN-WebAdmin#78]
hello friends 
The script was installed on Debian 10.
There is no edit user button
please guide me 

@dungpham91 
Regard

![Screenshot_51](https://user-images.githubusercontent.com/87688187/184818425-d111bece-ebab-49e7-b933-c9d1b3135ffd.png)

**Comment by shahrooz1349** [comment]
Does anyone have this problem?

**Comment by Bngladiator** [comment]
Hello. I have the same problem. Please tell me how did you solve this problem.
